### ISSUE TITLE
Auth & Profile 관련 unresolved TODO

### ISSUE THREAD

**Issue by gajagajago** [wafflestudio/guam-community-client#47]
### TODO

- [x] 서버와 클라 간 user scheme align. (현재 profileImg 같은 거 없어서 터진 부분 많을 것)
- [x] 현재 /users/me 에 isProfileSet 같은 변수가 없어 회원가입 진행상황으로 넘어갈 수 없음. 서버 선 개발 필요.
- [ ] 카카오 토큰 --> 파베 토큰 --> 파베 로그인 시간 소요 긺. 이때 보여줄 circularProgress 도입 + 적용 
- [ ] kakao native app key 등 github secrets로 관리
